# fly.toml app configuration file generated for palmetto-test on 2023-10-27T10:51:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "palmetto-test"
primary_region = "sjc"
